#!/bin/bash

REPO_ROOT=$(git rev-parse --show-toplevel)

cd "$REPO_ROOT" || exit 1

echo "Running pre-push checks..."

if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

echo "🔍 Running Ruff import sorting check..."
if ! ruff check . --select I --fix; then
    echo "❌ Import sorting check failed. Push aborted."
    echo "Please review the changes and try again."
    exit 1
fi
echo "✅ Import sorting check complete."

echo "🔍 Running Ruff format check..."
if ! ruff format --check .; then
    echo "Running automatic formatting..."
    ruff format .

    if ! git diff --quiet; then
        git add .
        git commit -m "style: auto-format code with Ruff"
        echo "✅ Formatting changes have been automatically committed."
    fi
fi
echo "✅ Code formatting check complete."

echo "🧪 Running tests..."
if ! .venv/bin/pytest tests/; then
    echo "❌ Tests failed. Push aborted."
    echo "Please fix the failing tests before pushing."
    exit 1
fi

echo "✅ All checks passed. Proceeding with push."
exit 0